### ISSUE TITLE
Soulbound Axes not Stripping Logs in 1.19.4 with ItemSoulBind version 1.6

### ISSUE THREAD

**Issue by Bacore** [mk7a-mc/ItemSoulBind#39] opened 2023-06-07 17:17 UTC
**Plugin version**
1.6

**Spigot Version**
Current: git-Purpur-1967 (MC: 1.19.4)*
Previous: git-Purpur-1933 (MC: 1.19.3)
* You are 15 version(s) behind

**Plugin Configuration**
<details>
# When player interacts with an item with the register string in its lore, item will be soul bound to them
registerString: "%soulsecure%"
# Group bind string
#   Place permission after this string, terminated by a space or end of line
#   Example: %soulbindgroup%perm which will have permission itemsoulbind.group.perm
groupRegisterString: "%soulbindgroup%"

# SPECIAL BINDS - items with relevant bind string will only be bound in the specified conditions
# Color is ignored when checking for string. Case-sensitive.

# Binds when tool is used: used to break block, sword used to hit entity
bindOnUse: false
bouString: "&9Soul binds on use"
# Binds when armor is equipped through in-hand right click
bindOnEquip: false
boeString: "&9Soul binds on equip"
# Binds when item is picked up
bindOnPickup: true
bopString: "&9Soul binds on pickup"

# Disable soul bind particle+sound effects
disableEffects: false

# Display message in item lore of soul bound item
# Use %username% for player name placeholder
displayLoreMsg: true
loreMsg: "&9Soul bound to %username%"
# Similarly for group binds, using placeholder %group%
displayLoreMsgGroup: true
loreMsgGroup: "&9Soul bound to group %group%"

# Log player detected with item soul bound to another player in console
consoleLogDetection: true

# Prevents placing soul bound blocks
preventPlacing: true

# Prevents crafting with soul bound items
preventCraft: false

# Prevents enchanting with soul bound items
preventEnchant: false

# Prevents anvil use with soul bound items
preventAnvil: false

# Blocks commands when soul bound item is held in hand
# Only provide the first part of the command, e.g. for "/auction sell" :
blockedCommands:
  - "auction"

# =======================
# Messages | use '&' for color codes
msgPrefix: "&8[&bSoul&3Bind&8]&r "
denyMsg: "&9This item is soul bound to another player"
denyMsgGroup: "&9This item is soul bound"
detectedItemMessage: "&cAn item soul bound to another player was removed from your inventory. Event has been logged."
detectedItemMessageGroup: "&cA soul bound item that you do not have access to has been detected in your inventory. Event has been logged."
detectedItemBroadcast: "was detected with an item soul bound to another player."
detectedItemBroadcastGroup: "was detected with a soul bound item they do not have access to."
noPermissionGeneric: "&cInsufficient permissions."
noPermissionBindOthers: "&cInsufficient permissions to bind for other players."
bindSuccess: "&aSoul bind complete."
bindErrorHeldItem: "You must be holding an item in your main hand."
bindErrorAlreadyBound: "This item is already soul bound."
bindErrorNoSuchPlayer: "No such player found online."
bindErrorRemoteNoItem: "Specific target player inventory slot is empty."
unbindErrorNotBound: "Item is not soul bound."
unbindSuccess: "&aSoul bind removed."
inventoryProcessSuccess: "&aProcessed inventory of "
craftDeny: "&cCannot craft with soul bound items."
enchantDeny: "&cCannot enchant soul bound items."
anvilDeny: "&cCannot use anvil on soul bound items."
foundItems: "&7Soul bound items found with another player have been returned to you. Use &b/returnItems &7to get them."
noItems: "You have no items to retrieve."
specialBindDone: "&aSpecial bind applied to item."
cmdBlocked: "&cCannot perform this command on a soul bound item."
# ======================

configVersionDoNotModify: 1.6
</details>

**Plugins List**
AdvancedTeleport-Bukkit-5.6.7.jar
AntiVillagerLag-2.3.1.jar
Autorank-5.2.1.jar
BKCommonLib-1.19.4-v1-1547.jar
BungeeGuard.jar
ChestSort-13.6.0.jar
Chunky-1.3.52.jar
ChunkyBorder-1.1.42.jar
Citizens-2.0.31-b3070.jar
CitizensCMD-2.6.11.jar
CMI-9.5.1.2.jar
CMIEInjector1.0.2.3.jar
CMILib1.2.5.5.jar
CoreProtect-21.3.jar
DeluxeTags-1.8.2-Release.jar
Denizen-1.2.7-b1792-REL.jar
DiscordSRV-Build-1.26.2.jar
dtlTradersPlus-6.4.18.jar
Dynmap-3.5-spigot.jar
InvUnload-5.0.2.jar
ipwhitelist-1.7-3.jar
ItemSoulBind-1.6.0.jar
LuckPerms-Bukkit-5.4.79.jar
MiniaturePets-3.0.2.jar
MyWorlds-1.19.4-v1-225.jar
OpenInv.jar
PlaceholderAPI-2.11.3.jar
ProtocolLib.jar
PvPManager.jar
ShulkerPacks-1.6.4.jar
SinglePlayerSleep-1.13_2.13.49.jar
Skulls.jar
TAB-Bridge v2.0.12.jar
tabtps-spigot-1.3.17.jar
TrElytra.jar
Vault.jar
VentureChat-3.5.0.jar
VillagerModifications-1.5.2.jar
worldedit-bukkit-7.2.14.jar
worldguard-bukkit-7.0.8-beta-01-dist.jar

**To Reproduce**
Use any axe (seems like any vanilla enchants or better like Efficiency 8) and you can strip logs like normal. But use /binditem on it and it will no longer strip logs. It will give the appearance of stripping the log but then revert to a normal log.

**Expected behavior**
Soulbound axes should be able to strip logs.

**Screenshots**
N/A

**Additional context**
We've used itemsoulbind since 1.18 and I think we would have noticed this before now? But perhaps not.

**Comment by Bacore** [comment] 2023-06-07 17:34
Additionally I cannot un-wax copper. I imagine that it is for the same reason.

**Comment by mk7a** [comment] 2023-06-09 20:09
Unable to reproduce on latest paper 1.19.4
Try a binary search on your other plugins to find a conflict.

**Comment by mk7a** [comment] 2023-06-14 11:08
Fixed in 1.6.1

**Closed by mk7a** 2023-06-14 11:08 UTC
